name: getx_clean
description: Change description
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get: ^4.1.4
  get_storage: ^2.0.2
  flutter_screenutil: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Airbnb
      fonts:
        - asset: assets/fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCerealMedium.ttf
          weight: 500
        - asset: assets/fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCerealBlack.ttf
          weight: 800
        - asset: assets/fonts/AirbnbCerealBlack.ttf
          weight: 900